OperationsHistoryService:
    Db:
        LogsConnString:
            settings-key: OperationsHistoryService-LogsConnString
            types:
              - AzureTableStorage
        DataConnString:
            settings-key: OperationsHistoryService-DataConnString
    RabbitMq:
        RabbitMqConnectionString:
            settings-key: WalletManagementRabbitMQ
            types:
              - RabbitMq
    CustomerWalletCacheExpirationPeriod:
        settings-key: OperationsHistoryService-CustomerWalletCacheExpirationPeriod
    IsPublicBlockchainFeatureDisabled:
        settings-key: IsPublicBlockchainFeatureDisabled
        types:
            - Optional
CampaignService:
    ServiceUrl:
        settings-key: CampaignServiceUrl
PrivateBlockchainFacadeClient:
    ServiceUrl:
        settings-key: PrivateBlockchainFacadeServiceUrl
PartnerManagementService:
  ServiceUrl:
    settings-key: PartnerManagementServiceUrl
CustomerProfileService:
    ServiceUrl :
        settings-key: CustomerProfileServiceUrl
SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName:
            settings-key: SlackQueueName
MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl
Constants:
    TokenSymbol:
        settings-key: Constant-TokenSymbol

